<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name','user_id','tenant_id'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->user_id = auth('api')->user()->id;
            $model->tenant_id = auth('api')->user()->current_tenant_id;
        });
    }
}
